import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {calculateRound, rulesetFor, totalsFor, gameOutcome, playerStats} from './rules.js';

assert.equal(calculateRound({numbers:[3,7,11],doubled:true,modifiers:[4,10],flip7:true}),71);
assert.equal(calculateRound({numbers:[12],doubled:true,modifiers:[10],flip7:true,busted:true}),0);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],divided:true,penalties:[4],flip7:false}),12);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],divided:true,penalties:[2,10],flip7:true}),19);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],specialZero:true,flip7:false}),0);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],specialZero:true,flip7:true}),15);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[13],lucky13:true}),26);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[1],penalties:[10]}),0);
assert.equal(rulesetFor({}).id,'classic','saved games without a ruleset must remain classic');
assert.equal(rulesetFor({ruleset:'vengeance'}).numberMax,13);
const game={target:200,playerIds:['a','b'],rounds:[{scores:{a:100,b:90}},{scores:{a:100,b:110}}]};
assert.deepEqual(totalsFor(game),{a:200,b:200});
assert.deepEqual(gameOutcome(game).tied,true);
game.rounds.push({scores:{a:10,b:5}});
assert.equal(gameOutcome(game).leaders[0],'a');
assert.equal(gameOutcome(game).finished,true);
const complete={...game,id:'g',status:'complete',winnerId:'a',completedAt:'2026-07-19T00:00:00Z'};
const stats=playerStats([{id:'a',name:'A'},{id:'b',name:'B'}],[complete]);
assert.equal(stats[0].wins,1);assert.equal(stats[1].wins,0);assert.equal(stats[0].games,1);
const index=readFileSync(new URL('./index.html',import.meta.url),'utf8');
const privacy=readFileSync(new URL('./privacy.html',import.meta.url),'utf8');
const update=readFileSync(new URL('./update.html',import.meta.url),'utf8');
const app=readFileSync(new URL('./app.js',import.meta.url),'utf8');
const worker=readFileSync(new URL('./sw.js',import.meta.url),'utf8');
const receiver=readFileSync(new URL('./cast-receiver/receiver.js',import.meta.url),'utf8');
const receiverCss=readFileSync(new URL('./cast-receiver/receiver.css',import.meta.url),'utf8');
const build=index.match(/application-version" content="(\d+)"/)?.[1];
assert.ok(build,'index must declare an application version');
assert.match(privacy,new RegExp(`App version ${build}`));
assert.match(update,new RegExp(`Opening version ${build}`));
assert.match(app,new RegExp(`const BUILD = '${build}'`));
assert.match(worker,new RegExp(`flipcast-v${build}`));
assert.match(index,/<title>FlipCast<\/title>/,'app title must use the FlipCast brand');
assert.match(receiver,/FlipCast/,'Cast receiver must use the FlipCast brand');
assert.match(app,new RegExp(`register\\('\\./sw\\.js\\?v=${build}'`));
assert.match(update,new RegExp(`register\\('\\./sw\\.js\\?v=${build}'`));
assert.doesNotMatch(worker,/cache\.put\(request\.mode\s*===\s*['"]navigate['"]/);
assert.match(app,/querySelector\(['"]button\.chip\.double['"]\)/,'×2 handler must target the button, not the active ×2 badge');
assert.match(app,/window\.visualViewport\?\.height\|\|window\.innerHeight/,'mobile shell must track the live visual viewport height');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/requestInFlight/,'Cast sender must suppress overlapping session requests');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/autoJoinPolicy: chrome\.cast\.AutoJoinPolicy\.PAGE_SCOPED, resumeSavedSession:false/,'Cast sender must not auto-resume stale origin-wide sessions');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/clearStaleSession/,'Cast sender must clear failed sessions before requesting a new one');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/attempt < 10/,'Cast sender must wait a bounded interval for stale session cleanup');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/recoverSender\(code\)/,'Cast sender must recover in-app after a failed request');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/await delay\(250\)[\s\S]*await castContext\.requestSession\(\)/,'Cast sender must make one bounded automatic retry after a reset');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/if \(connectedState\(currentSessionState\(\)\)\)[\s\S]*await castContext\.requestSession\(\)/,'Tapping Cast while connected must open the Cast management dialog');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/pendingScoreboard = \{scoreboard, attempts:0\}/,'Cast updates must retain the latest state until it is delivered');
assert.match(readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8'),/envelope\.attempts >= 4/,'Cast message delivery retries must remain bounded');
assert.match(app,/visualViewport\?\.addEventListener\(['"]resize['"],syncViewportHeight\)/,'mobile shell must react to browser-bar viewport changes');
assert.match(app,/data-ruleset="classic"/,'new-game flow must offer classic Flip 7');
assert.match(app,/data-ruleset="vengeance"/,'new-game flow must offer With a Vengeance');
assert.match(app,/ruleset:setupRuleset/,'new games must persist their selected ruleset');
assert.match(app,/g\.ruleset\|\|'classic'/,'old games must calculate as classic');
assert.match(receiver,/cols=players\.length>=6\?2:1/,'Cast receiver must use two columns for six or more players');
assert.match(receiver,/effectQueue=\[\],activeEffectKeys=new Set\(\)/,'Cast receiver must track queued and playing effects independently');
assert.match(receiver,/MAX_ACTIVE_EFFECTS=1/,'Cast receiver must use only one decoder-heavy video at a time');
assert.match(receiver,/MAX_PLAYBACK_RETRIES=1/,'Persistent media failures must have one bounded retry');
assert.match(receiver,/else effectState\.set\(key,'done'\)/,'Persistent media failures must terminate instead of requeueing forever');
assert.match(receiver,/video\.pause\(\);video\.remove\(\)/,'Abandoned effects must release their decoder immediately');
assert.match(receiver,/START_TIMEOUT_MS=4500,STALL_GRACE_MS=1400/,'Cast playback must use bounded startup and stall detection');
assert.match(receiver,/data\.status==='stats'/,'Cast receiver must render all-time statistics');
assert.match(app,/status:'stats'/,'Sender must publish a dedicated Cast statistics payload');
assert.match(app,/else if\(next==='stats'\)sendStatsToCast\(\)/,'Opening app statistics must update an active Cast session');
assert.match(receiver,/\['electric',p\.nearVictory\]/,'Near-win treatment must use the queued electric video');
assert.match(receiver,/players\.flatMap\(p=>videoEffects\(p\)\.map/,'Cast receiver must queue every simultaneous player effect, not only the highest-priority one');
assert.match(receiver,/board\.addEventListener\('playing'/,'Video artwork must become visible only after playback actually starts');
assert.doesNotMatch(receiver,/onloadeddata=.*ready/,'A decoded first frame must not be mistaken for active playback');
assert.match(receiver,/board\.addEventListener\('waiting',stall,true\)/,'A stalled video must enter bounded failure recovery');
assert.match(receiver,/image\.decoding='async'/,'Warm-up must decode lightweight artwork without preloading every heavy video');
assert.doesNotMatch(receiver,/active-poster/,'Legacy artwork must never be inserted before an effect video');
assert.match(receiver,/activeEffect\?vfxVideo\(activeEffect,key\):''/,'Active effects must contain only the video, without a pre-video poster');
assert.match(receiver,/effectState\.set\(key,'done'\)/,'Completed videos must release their queue slot');
assert.match(receiver,/board\.addEventListener\('ended'.*finishVideo/,'Completed videos must advance the effect queue');
assert.match(receiver,/heldEffects\.set\(playerKey\(key\),key\.slice/,'Every completed video must retain a decoder-free final treatment');
assert.match(receiver,/const frozenFx=/,'Completed effects must render from a dedicated post-video still layer');
assert.match(receiverCss,/\.player-fx\.effect-frozen/,'Frozen final treatments must remain lightweight and decoder-free');
assert.match(receiver,/flip7:\{file:'flip7-v60\.webm'/,'Flip 7 must use the approved photoreal gold video');
assert.match(receiver,/fire:\{file:'fire-v49\.mp4',type:'video\/mp4',poster:'fire-v53-poster\.png'/,'Fire must hold the video-derived final frame');
assert.match(receiver,/freeze:\{file:'freeze-v49\.mp4',type:'video\/mp4',poster:'freeze-v53-poster\.png'/,'Freeze must hold the video-derived final frame');
assert.match(receiver,/electric:\{file:'electric-v49\.mp4',type:'video\/mp4',poster:'electric-v53-poster\.png'/,'Electric must hold the video-derived final frame');
assert.doesNotMatch(receiver,/poster:'(?:fire-v2|frost-v2|electric-v2)\.webp'/,'Legacy effect artwork must not be used for post-video stills');
assert.match(receiver,/effect==='x2'\?'<span>×2<\/span>'/,'The frozen ×2 final frame must retain its dedicated label');
assert.match(receiverCss,/\.player-fx\.fx-stage-electric\{background:#000\}/,'Near-win edge video must have a solid black center stage');
assert.match(receiverCss,/\.stats-screen\.dense-stats \.cast-stats\{[^}]*grid-template-rows:repeat\(9/,'Dense all-time stats must fit all 18 players in two compact columns');
assert.match(receiverCss,/\.cast-stat-row strong\{[^}]*text-overflow:ellipsis/,'Long stats names must remain inside their row');
assert.match(receiver,/⚡ NEAR WIN/,'Cast near-win badge must match the app wording');
assert.match(receiverCss,/fx-electric-video\.ready[^}]*mask-image/,'Near-win video must be masked to the card edges');
assert.doesNotMatch(receiver,/fx-near-edge/,'Near-win must not regress to nearly invisible CSS streaks');
console.log('All rules and statistics tests passed.');
