import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {calculateRound, rulesetFor, totalsFor, gameOutcome, playerStats} from './rules.js';

assert.equal(calculateRound({numbers:[3,7,11],doubled:true,modifiers:[4,10],flip7:true}),71);
assert.equal(calculateRound({numbers:[12],doubled:true,modifiers:[10],flip7:true,busted:true}),0);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],divided:true,penalties:[4],flip7:false}),12);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],divided:true,penalties:[2,10],flip7:true}),19);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],specialZero:true,flip7:false}),0);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[8,11,13],specialZero:true,flip7:true}),47);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[1,2,3,4,5,6],specialZero:true,flip7:true}),36);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[1,2,3,4,5,6],specialZero:true,flip7:false}),0);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[13],lucky13:true}),26);
assert.equal(calculateRound({ruleset:'vengeance',numbers:[1],penalties:[10]}),0);
assert.equal(rulesetFor({}).id,'classic','saved games without a ruleset must remain classic');
assert.equal(rulesetFor({ruleset:'vengeance'}).numberMax,13);
const game={target:200,playerIds:['a','b'],rounds:[{scores:{a:100,b:90}},{scores:{a:100,b:110}}]};
assert.deepEqual(totalsFor(game),{a:200,b:200});
assert.deepEqual(gameOutcome(game).tied,true);
game.rounds.push({scores:{a:10,b:5}});
assert.equal(gameOutcome(game).leaders[0],'a');
assert.equal(gameOutcome(game).finished,true);
const complete={...game,id:'g',status:'complete',winnerId:'a',completedAt:'2026-07-19T00:00:00Z'};
const stats=playerStats([{id:'a',name:'A'},{id:'b',name:'B'}],[complete]);
assert.equal(stats[0].wins,1);assert.equal(stats[1].wins,0);assert.equal(stats[0].games,1);
const index=readFileSync(new URL('./index.html',import.meta.url),'utf8');
const privacy=readFileSync(new URL('./privacy.html',import.meta.url),'utf8');
const update=readFileSync(new URL('./update.html',import.meta.url),'utf8');
const app=readFileSync(new URL('./app.js',import.meta.url),'utf8');
const worker=readFileSync(new URL('./sw.js',import.meta.url),'utf8');
const receiver=readFileSync(new URL('./cast-receiver/receiver.js',import.meta.url),'utf8');
const receiverCss=readFileSync(new URL('./cast-receiver/receiver.css',import.meta.url),'utf8');
const build=index.match(/application-version" content="(\d+)"/)?.[1];
assert.ok(build,'index must declare an application version');
assert.match(privacy,new RegExp(`App version ${build}`));
assert.match(update,new RegExp(`Opening version ${build}`));
assert.match(app,new RegExp(`const BUILD = '${build}'`));
assert.match(worker,new RegExp(`flipcast-v${build}`));
assert.match(index,/<title>FlipCast<\/title>/,'app title must use the FlipCast brand');
assert.match(receiver,/FlipCast/,'Cast receiver must use the FlipCast brand');
assert.match(app,new RegExp(`register\\('\\./sw\\.js\\?v=${build}'`));
assert.match(update,new RegExp(`register\\('\\./sw\\.js\\?v=${build}'`));
assert.doesNotMatch(worker,/cache\.put\(request\.mode\s*===\s*['"]navigate['"]/);
assert.match(app,/querySelector\(['"]button\.chip\.double['"]\)/,'×2 handler must target the button, not the active ×2 badge');
assert.match(app,/window\.visualViewport\?\.height\|\|window\.innerHeight/,'mobile shell must track the live visual viewport height');
const sender=readFileSync(new URL('./cast-sender.js',import.meta.url),'utf8');
assert.match(index,/<google-cast-launcher id="castButton"/,'The framework-owned Cast launcher must control session chooser interactions');
assert.doesNotMatch(sender,/requestSession\(/,'Sender code must not open the chooser outside the framework launcher user gesture');
assert.match(sender,/autoJoinPolicy:chrome\.cast\.AutoJoinPolicy\.ORIGIN_SCOPED,\s*resumeSavedSession:true/,'Cast sessions must restore consistently across the FlipCast origin');
assert.match(sender,/type:'HELLO'/,'Sender must wait for receiver readiness');
assert.match(sender,/message\.type === 'READY'/,'Sender must recognize receiver readiness');
assert.match(sender,/type:'STATE', seq:envelope\.seq/,'Scoreboard messages must use sequenced envelopes');
assert.match(sender,/message\.type === 'ACK'/,'Sender must confirm receiver rendering acknowledgements');
assert.match(sender,/MAX_SEND_ATTEMPTS = 5/,'Cast message delivery retries must remain bounded');
assert.match(sender,/pendingScoreboard = \{scoreboard, seq:nextSequence\+\+, attempts:0\}/,'Cast updates must retain only the latest state until acknowledged');
assert.match(app,/visualViewport\?\.addEventListener\(['"]resize['"],syncViewportHeight\)/,'mobile shell must react to browser-bar viewport changes');
assert.match(app,/data-ruleset="classic"/,'new-game flow must offer classic Flip 7');
assert.match(app,/data-ruleset="vengeance"/,'new-game flow must offer With a Vengeance');
assert.match(app,/ruleset:setupRuleset/,'new games must persist their selected ruleset');
assert.match(app,/g\.ruleset\|\|'classic'/,'old games must calculate as classic');
assert.match(receiver,/cols=players\.length>=6\?2:1/,'Cast receiver must use two columns for six or more players');
assert.match(receiver,/effectQueue=\[\],activeEffectKeys=new Set\(\)/,'Cast receiver must track queued and playing effects independently');
assert.match(receiver,/MAX_ACTIVE_EFFECTS=1/,'Cast receiver must use only one decoder-heavy video at a time');
assert.match(receiver,/MAX_PLAYBACK_RETRIES=1/,'Persistent media failures must have one bounded retry');
assert.match(receiver,/else effectState\.set\(key,'done'\)/,'Persistent media failures must terminate instead of requeueing forever');
assert.match(receiver,/video\.pause\(\);video\.remove\(\)/,'Abandoned effects must release their decoder immediately');
assert.match(receiver,/START_TIMEOUT_MS=4500,STALL_GRACE_MS=1400/,'Cast playback must use bounded startup and stall detection');
assert.match(receiver,/data\.status==='stats'/,'Cast receiver must render all-time statistics');
assert.match(app,/status:'stats'/,'Sender must publish a dedicated Cast statistics payload');
assert.match(app,/else if\(next==='stats'\)sendStatsToCast\(\)/,'Opening app statistics must update an active Cast session');
assert.match(receiver,/\['electric',p\.nearVictory\]/,'Near-win treatment must use the queued electric video');
assert.match(receiver,/players\.flatMap\(p=>videoEffects\(p\)\.map/,'Cast receiver must queue every simultaneous player effect, not only the highest-priority one');
assert.match(receiver,/video\._decodedFrames>=REVEAL_AFTER_FRAMES\)revealVideo\(video\)/,'Video artwork must remain hidden until several decoded frames are available');
assert.match(receiver,/video\.currentTime<REVEAL_AFTER_SECONDS/,'Video artwork must remain hidden through the cold decoder blank lead-in');
assert.doesNotMatch(receiver,/onloadeddata=.*ready/,'A decoded first frame must not be mistaken for active playback');
assert.match(receiverCss,/clip-path:inset\(50%\);transform:translateZ\(0\) scale\(\.001\)/,'Uninitialized Chromecast video surfaces must remain clipped and collapsed');
assert.match(receiver,/board\.addEventListener\('waiting',stall,true\)/,'A stalled video must enter bounded failure recovery');
assert.match(receiver,/image\.decoding='async'/,'Warm-up must decode lightweight artwork without preloading every heavy video');
assert.doesNotMatch(receiver,/paintAndCheckFrame\(video\)/,'Production video must not depend on unsupported hardware-surface canvas reads');
assert.doesNotMatch(receiver,/active-poster/,'Active effects must not flash held artwork before motion');
assert.match(receiver,/x2:\{file:'x2-v83\.mp4',type:'video\/mp4'/,'×2 must use Chromecast-native H.264 MP4');
assert.match(receiver,/bust:\{file:'bust-v83\.mp4',type:'video\/mp4'/,'Bust must use Chromecast-native H.264 MP4');
assert.match(receiver,/flip7:\{file:'flip7-v83\.mp4',type:'video\/mp4'/,'Flip 7 must use Chromecast-native H.264 MP4');
assert.doesNotMatch(receiver,/type:'video\/webm'/,'Cast effects must not use the unreliable WebM hardware path');
assert.match(receiver,/function warmVideoSource\(source,type\)/,'Approved videos must cold-start invisibly before reaching a player card');
assert.match(receiver,/video\.currentTime>=\.3/,'Decoder warm-up must advance through real motion frames');
assert.doesNotMatch(receiver,/warmApprovedVideos/,'Receiver startup must not download every approved video');
assert.match(receiver,/function warmPoster\(name\)/,'Only the active effect poster should be warmed');
assert.match(receiver,/data\.type==='HELLO'/,'Receiver must answer sender readiness probes');
assert.match(receiver,/type:'READY',receiverBuild:RECEIVER_BUILD/,'Receiver must identify its running build');
assert.match(receiver,/data\.type==='STATE'/,'Receiver must accept sequenced scoreboard state');
assert.match(receiver,/type:'ACK',seq,receiverBuild:RECEIVER_BUILD/,'Receiver must acknowledge each scoreboard state');
assert.match(receiver,/if\(seq>last\)/,'Receiver must render duplicate sequence retries only once');
assert.match(receiver,/context\.start\(\)/,'Receiver must use the standard CAF lifecycle');
assert.doesNotMatch(receiver,/autoplay muted playsinline/,'Player videos must not auto-start before decoder warm-up completes');
assert.match(receiver,/effectState\.set\(key,'done'\)/,'Completed videos must release their queue slot');
assert.match(receiver,/board\.addEventListener\('ended'.*finishVideo/,'Completed videos must advance the effect queue');
assert.match(receiver,/heldEffects\.set\(playerKey\(key\),key\.slice/,'Every completed video must retain a decoder-free final treatment');
assert.match(receiver,/const frozenFx=/,'Completed effects must render from a dedicated post-video still layer');
assert.match(receiverCss,/\.player-fx\.effect-frozen/,'Frozen final treatments must remain lightweight and decoder-free');
assert.match(receiver,/flip7:\{file:'flip7-v83\.mp4'/,'Flip 7 must use the approved photoreal gold video in Chromecast-native packaging');
assert.match(receiver,/fire:\{file:'fire-v49\.mp4',type:'video\/mp4',poster:'fire-v53-poster\.png'/,'Fire must hold the video-derived final frame');
assert.match(receiver,/freeze:\{file:'freeze-v49\.mp4',type:'video\/mp4',poster:'freeze-v53-poster\.png'/,'Freeze must hold the video-derived final frame');
assert.match(receiver,/electric:\{file:'electric-v85\.mp4',type:'video\/mp4',poster:'electric-v85-poster\.png'/,'Electric must use and hold the approved full-frame Near Win video');
assert.match(receiver,/divide:\{file:'divide-v91\.mp4',type:'video\/mp4',poster:'divide-v91-poster\.png'/,'Divide by 2 must use the approved tightly cropped Flow saber-cut video and its held label');
assert.match(receiver,/divide:\{file:'divide-v91\.mp4',type:'video\/mp4',poster:'divide-v91-poster\.png',holdAt:5\.75\}/,'Divide by 2 must force its poster handoff without relying on an ended event');
assert.match(receiver,/video\._frameTimer=setTimeout\(\(\)=>revealVideo\(video\),220\);if\(video\.requestVideoFrameCallback\)/,'Every playing video must have a timed reveal fallback even when frame callbacks exist');
assert.match(receiver,/lucky13:\{file:'lucky13-v86\.mp4',type:'video\/mp4',poster:'lucky13-v86-poster\.png'/,'Lucky 13 must use the approved subtle jewel-tone video');
assert.match(receiver,/\['lucky13',p\.lucky13\],\['divide',p\.divided\]/,'Vengeance draft flags must enter the Cast effect queue');
assert.match(app,/divided:Boolean\(d\?\.divided\),lucky13:Boolean\(d\?\.lucky13\)/,'Cast payload must send Divide by 2 and Lucky 13 draft state');
assert.doesNotMatch(receiver,/poster:'(?:fire-v2|frost-v2|electric-v2)\.webp'/,'Legacy effect artwork must not be used for post-video stills');
assert.match(receiver,/effect==='x2'\?'<span>×2<\/span>'/,'The frozen ×2 final frame must retain its dedicated label');
assert.match(receiverCss,/\.player-fx\.fx-stage-electric\{background:transparent\}/,'Near-win edge video must not cover the card center with a black rectangle');
assert.match(receiverCss,/\.fx-flip7-poster,\.player-fx \.fx-flip7-video,\.player-fx \.fx-flip7-canvas\{object-fit:fill/,'Flip 7 must adapt to every player-card aspect ratio');
assert.match(receiverCss,/\.stats-screen\.dense-stats \.cast-stats\{[^}]*grid-template-rows:repeat\(9/,'Dense all-time stats must fit all 18 players in two compact columns');
assert.match(receiverCss,/\.cast-stat-row strong\{[^}]*text-overflow:ellipsis/,'Long stats names must remain inside their row');
assert.match(receiver,/⚡ NEAR WIN/,'Cast near-win badge must match the app wording');
assert.match(receiverCss,/fx-electric-video\.ready[^}]*clip-path:none/,'Near-win video must fill the player card without a center cutout');
assert.doesNotMatch(receiverCss,/fx-electric-video\.ready[^}]*clip-path:polygon\(evenodd/,'Near-win must not reintroduce a compositor-cut center hole');
assert.doesNotMatch(receiver,/fx-near-edge/,'Near-win must not regress to nearly invisible CSS streaks');
console.log('All rules and statistics tests passed.');
